# tasks file for hipchat
---
- name: install | dependencies
  apt:
    name: "{{ hipchat_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - hipchat-install-dependencies
