# tasks file for hipchat
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ hipchat_dependencies }}"
  tags:
    - hipchat-install-dependencies
