# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ hipchat_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - hipchat-install-dependencies
