# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - hipchat
    - hipchat-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - hipchat
    - hipchat-install
