# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ hipchat_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - hipchat-repository-install-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: EBA59E53CC64091D
    url: https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public
    state: present
  tags:
    - hipchat-repository-public-key

- name: repository | add hipchat repository
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ hipchat_repositories }}"
  tags:
    - hipchat-repository-add
