# tasks file for hipchat
---
- name: add public key
  apt_key:
    id: AAD4AA21729B5780
    url: https://www.hipchat.com/keys/hipchat-linux.key
    state: present
  tags:
    - hipchat-repository-public-key

- name: add hipchat repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ hipchat_repositories }}"
  tags:
    - hipchat-repository-add
